### ISSUE TITLE
DJWorker Options Help

### ISSUE THREAD

**Issue by nikmauro** [seatgeek/djjob#40]
Please explain the Djworker options

```php
$options = array_merge(array(
            "queue" => "default",
            "count" => 0,
            "sleep" => 5,
            "max_attempts" => 5,
            "fail_on_output" => false
        )
```

**Comment by AndrewEQ** [comment]
queue - the name of the queue you want to pull jobs from
count - the number of jobs to run before exiting
sleep - seconds to sleep after finding no new jobs
max attempts - how many times to try a failed job
fail_on_output - if true, it will throw an error if your job produces output like echoing a string.
