### ISSUE TITLE
QuickFix - Solution provided - shell_exec() has been disabled for security reasons

### ISSUE THREAD

**Issue by AndrewEQ** [seatgeek/djjob#42]
On line https://github.com/seatgeek/djjob/blob/master/DJJob.php#L217, the "\`hostname\`" throws the following error in strict environments: "shell_exec() has been disabled for security reasons"

Fix: replace "\`hostname\`" with "gethostname()".

**Comment by josegonzalez** [comment]
Merged, thanks for the pr.

**Comment by AndrewEQ** [comment]
You're welcome!
